name: SkechersInventory
options:
  bundleIdPrefix: com.skechers
  deploymentTarget:
    iOS: 17.0
  developmentLanguage: en
  xcodeVersion: "15.0"

settings:
  SWIFT_VERSION: 5.9
  IPHONEOS_DEPLOYMENT_TARGET: 17.0

packages:
  GRDB:
    url: https://github.com/groue/GRDB.swift.git
    from: 6.24.0

targets:
  SkechersInventory:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: SkechersInventory
    dependencies:
      - package: GRDB
    info:
      path: SkechersInventory/Info.plist
      properties:
        CFBundleDisplayName: Skechers Inventory
        CFBundleIdentifier: com.skechers.inventory
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        NSCameraUsageDescription: "We need camera access to scan shoe tags"
        NSPhotoLibraryUsageDescription: "We need photo library access to select shoe tag images"
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.skechers.inventory
      INFOPLIST_FILE: SkechersInventory/Info.plist
      SWIFT_VERSION: 5.9
      TARGETED_DEVICE_FAMILY: "1,2"
